apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment #name of the configuration
spec:
  replicas: 1 #no of identical pods
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: hakunamatata007/multi-client
          ports:
            - containerPort: 3000
